using RoR2;
using Nautilus.Configuration;
using System;
using R2API;
using UnityEngine;
using UnityEngine.AddressableAssets;
using HarmonyLib;
using UnityEngine.Networking;
using RoR2.Items;

namespace Nautilus.Items
{
    public static partial class ItemInit
    {
        public static MotherOfPearl MotherOfPearl = new MotherOfPearl
        (
            "MotherOfPearl",
            [ItemTag.Damage, ItemTag.AIBlacklist],
            ItemTier.VoidTier3
        );
    }

    /// <summary>
    ///     // Ver.1
    /// 
    /// </summary>
    public class MotherOfPearl : ItemBase
    {
        public override bool Enabled => MotherOfPearl_Enabled.Value;
        public override ItemDef ConversionItemDef => Addressables.LoadAssetAsync<ItemDef>("RoR2/DLC2/Items/BarrageOnBoss/BarrageOnBoss.asset").WaitForCompletion();
        public override GameObject itemPrefab => OverwritePrefabMaterials();
        public Material material0 => Addressables.LoadAssetAsync<Material>("RoR2/DLC1/voidstage/matVoidTerrain.mat").WaitForCompletion();
        public Material material1 => Addressables.LoadAssetAsync<Material>("RoR2/Base/BonusGoldPackOnKill/matTomeGold.mat").WaitForCompletion();
        public override Sprite itemIcon => Main.Assets.LoadAsset<Sprite>("Assets/icons/motherOfPearl.png");
        public GameObject moneyPackPrefab => Addressables.LoadAssetAsync<GameObject>("RoR2/Base/BonusGoldPackOnKill/BonusMoneyPack.prefab").WaitForCompletion();

        public MotherOfPearl(string _name, ItemTag[] _tags, ItemTier _tier, bool _canRemove = true, bool _isConsumed = false, bool _hidden = false) : 
        base(_name, _tags, _tier, _canRemove, _isConsumed, _hidden){}

        // Config
        public static ConfigItem<bool> MotherOfPearl_Enabled = new ConfigItem<bool>
        (
            "Void legendary: Mother Of Pearl",
            "Item enabled",
            "Should this item appear in runs?",
            true
        );
        public static ConfigItem<int> MotherOfPearl_MissilesLaunched = new ConfigItem<int>
        (
            "Void legendary: Mother Of Pearl",
            "Missiles launched",
            "How many missiles to launch on gold pickup",
            3,
            1f,
            10f,
            1f
        );
        public static ConfigItem<float> MotherOfPearl_DamageCoeff = new ConfigItem<float>
        (
            "Void legendary: Mother Of Pearl",
            "Missile damage",
            "Missile damage in percentage",
            300f,
            100f,
            1000f,
            100f
        );
        public static ConfigItem<float> MotherOfPearl_DamageCoeffStack = new ConfigItem<float>
        (
            "Void legendary: Mother Of Pearl",
            "Missile damage (per stack)",
            "Missile damage in percentage, per additional stack",
            300f,
            100f,
            1000f,
            100f
        );
        public static ConfigItem<float> MotherOfPearl_PickupConvert = new ConfigItem<float>
        (
            "Void legendary: Mother Of Pearl",
            "Gold convert chance",
            "Flat fractional chance for any pickup generated by the holder to convert into a gold chunk",
            0.1f,
            0f,
            1f,
            0.01f
        );

        public GameObject OverwritePrefabMaterials()
        {
            GameObject ret = Main.Assets.LoadAsset<GameObject>("Assets/prefabs/motherOfPearl.prefab");

            Material[] materials =
            {
                material0,
                material1
            };
            ret.GetComponentInChildren<MeshRenderer>().SetMaterialArray(materials);

            return ret;
        }

        
        // Tokens
        public override void FormatDescriptionTokens()
        {
            string descriptionToken = ItemDef.descriptionToken;

            LanguageAPI.AddOverlay
            (
                descriptionToken,
                String.Format
                (
                    Language.currentLanguage.GetLocalizedStringByToken(descriptionToken),
                    MotherOfPearl_MissilesLaunched.Value,
                    MotherOfPearl_DamageCoeff.Value,
                    MotherOfPearl_DamageCoeffStack.Value,
                    MotherOfPearl_PickupConvert.Value * 100f
                )
            );
        }

        // Hooks
        public override void RegisterHooks()
        {
            // Add/remove behavior on inventory change
            On.RoR2.CharacterBody.OnInventoryChanged += (orig, self) =>
            {
                orig(self);

                MotherOfPearlBehavior behavior = self.GetComponent<MotherOfPearlBehavior>();
                int itemCount = GetItemCountEffective(self);

                if (GetItemCountEffective(self) > 0 && !behavior)
                {
                    behavior = self.AddItemBehavior<MotherOfPearlBehavior>(itemCount);
                    behavior.missiles = MotherOfPearl_MissilesLaunched.Value;
                }

                if (behavior)
                {
                    behavior.stack = itemCount;
                    behavior.damageCoeff = (MotherOfPearl_DamageCoeff.Value + (MotherOfPearl_DamageCoeffStack.Value * (itemCount - 1))) / 100f;
                }

                if(GetItemCountEffective(self) <= 0 && behavior)
                {
                    UnityEngine.Object.Destroy(self.GetComponent<MotherOfPearlBehavior>());
                }
            };
            
            // Launch a missile
            On.RoR2.MoneyPickup.OnTriggerStay += (orig, self, other) =>
            {
                if (!NetworkServer.active || !self.alive)
                {
                    return;
                }

                TeamIndex objectTeam = TeamComponent.GetObjectTeam(other.gameObject);
                if (objectTeam == self.teamFilter.teamIndex && other.TryGetComponent(out CharacterBody body) && body.TryGetComponent(out MotherOfPearlBehavior behavior))
                {
                    behavior.Trigger();
                }

                orig(self, other);
            };

            // Replacing pickups
            On.RoR2.AmmoPickup.ctor += (orig, self) =>
            {
                if (CheckGoldPickupRoll())
                {
                    SpawnGoldPickup(self.transform);
                    //UnityEngine.Object.Destroy(self.baseObject);
                }
                else
                {
                    orig(self);
                }
            };
        }

        public bool CheckGoldPickupRoll()
        {
            float totalRoll = 0f;

            var teamComponents = TeamComponent.GetTeamMembers(TeamIndex.Player);
            foreach (TeamComponent teamComponent in teamComponents)
            {
                if (teamComponent.body && GetItemCountEffective(teamComponent.body) > 0)
                {
                    totalRoll += MotherOfPearl_PickupConvert.Value * 100f;
                }
            }

            return Util.CheckRoll(totalRoll);
        }

        public void SpawnGoldPickup(Transform origTransform)
        {
            GameObject gameObject = UnityEngine.Object.Instantiate(moneyPackPrefab, origTransform.position, UnityEngine.Random.rotation);
            if ((bool)gameObject)
            {
                Collider component = gameObject.GetComponent<Collider>();
                Physics.IgnoreCollision(component, gameObject.GetComponent<Collider>());
                TeamFilter component2 = gameObject.GetComponent<TeamFilter>();
                if ((bool)component2)
                {
                    component2.teamIndex = TeamIndex.Player;
                }
                MoneyPickup componentInChildren = gameObject.GetComponentInChildren<MoneyPickup>();
                if ((bool)componentInChildren)
                {
                    componentInChildren.baseGoldReward = 25;
                    Physics.IgnoreCollision(component, componentInChildren.GetComponent<Collider>());
                }
                GravitatePickup componentInChildren2 = gameObject.GetComponentInChildren<GravitatePickup>();
                if ((bool)componentInChildren2)
                {
                    Physics.IgnoreCollision(component, componentInChildren2.GetComponent<Collider>());
                }
                gameObject.transform.localScale = Vector3.one * 1f;
                NetworkServer.Spawn(gameObject);
            }
        }
    }

    public class MotherOfPearlBehavior : CharacterBody.ItemBehavior
    {
        public int missiles = 0;
        public float damageCoeff = 0f;
        public float interval = 0.33f;
        public float timer = 0f;
        public int missileQueue = 0;

        public void Trigger()
        {
            missileQueue += missiles;
        }

        void FixedUpdate()
        {
            timer += Time.fixedDeltaTime;
            if (timer > interval && missileQueue > 0)
            {
                MissileUtils.FireMissile
                (
                    body.corePosition,
                    body,
                    new ProcChainMask(),
                    null,
                    damageCoeff * body.damage,
                    body.RollCrit(),
                    GlobalEventManager.CommonAssets.missilePrefab,
                    DamageColorIndex.Item,
                    true
                );

                missileQueue--;
            }
        }
    }
}